source 'http://rubygems.org'

gem 'rake'
gem 'colored', '~> 1.2'
gem 'git', require: false
gem 'json', '~> 1.8'
gem 'ffi', '~> 1.9.18'
gem 'openstudio-standards', '0.2.9'
gem 'aes', '~> 0.5.0'
gem 'geocoder', '~> 1.4.4'
gem 'highline', '~> 2.0.3'
gem 'launchy', '~> 2.4.3'
gem 'public_suffix', '3.1.1'

gem 'minitest', '~> 5.9'
gem 'rubocop', '~> 0.60.0'
gem 'rubocop-checkstyle_formatter', '~> 0.4.0'
gem 'ci_reporter_minitest', '~> 1.0.0'
gem 'simplecov', '~> 0.17.1'
gem 'simplecov-html', '~> 0.10.0'
gem 'minitest-reporters'
