__title__ = 'ResStock'
__description__ = 'Modeling the existing building stock (residential and commercial) using OpenStudio/EnergyPlus.'
__url__ = 'http://github.com/NREL/resstock'
__resstock_version__ = '2.5.0'
__os_version__ = '3.3.0'
__author__ = 'National Renewable Energy Laboratory'
__license__ = 'BSD-3'
__copyright__ = 'Copyright (c) 2016-2019, Alliance for Sustainable Energy, LLC.'