name: ci

on:
  push:
    branches: [ master, develop ]
  pull_request:
    types: [ synchronize, opened ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://nrel/openstudio:3.2.1
    steps:
      - name: Show environment
        run: |
          bundle -v
          ruby -v

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install gems
        run: |
          rm -f Gemfile.lock && bundle install

      - name: Update all measures
        run: |
          rake update_measures

      - name: Regenerate test osms
        run: |
          rake test:regenerate_osms

      - name: Run all unit tests
        run: |
          rake test:unit_tests

      - name: Run all project tests
        run: |
          rake test:project_tests

      - name: Run all analysis tests
        run: |
          rake test:analysis_tests

      - name: Upload feature samples
        uses: actions/upload-artifact@v2
        with:
          path: resources/buildstock.csv
          name: samples

      - name: Upload schedules
        uses: actions/upload-artifact@v2
        with:
          path: resources/measures/ResidentialScheduleGenerator/tests/output/test_sweep_building_ids_and_num_occupants
          name: schedules

  bsb:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Show environment
        run: |
          ruby -v
          python -v

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run buildstockbatch
        run: |
          pip install git+https://github.com/NREL/buildstockbatch.git@develop
          
          buildstock_docker project_national/national_baseline.yml
          buildstock_docker project_testing/testing_baseline.yml
          
          buildstock_docker project_national/national_upgrades.yml
          buildstock_docker project_testing/testing_upgrades.yml

      - name: Process results
        run: |
          gunzip -v project_national/national_baseline/results_csvs/*.csv.gz
          gunzip -v project_testing/testing_baseline/results_csvs/*.csv.gz
          
          gunzip -v project_national/national_upgrades/results_csvs/*.csv.gz
          gunzip -v project_testing/testing_upgrades/results_csvs/*.csv.gz
          
          pip install pandas
          
          python test/util.py

      - name: Upload integration results
        uses: actions/upload-artifact@v2
        with:
          path: |
            baseline
            upgrades
          name: results

  compare-results:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: bsb
    steps:
      - name: Show environment
        run: |
          ruby -v
          python -v

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.sha }}

      - name: Upload base samples and results
        uses: actions/upload-artifact@v2
        with:
          path: |
            test/test_samples_osw/baseline
            test/test_samples_osw/upgrades
          name: base

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Download base samples and results
        uses: actions/download-artifact@v2
        with:
          path: base
          name: base

      - name: Download feature samples
        uses: actions/download-artifact@v2
        with:
          path: samples
          name: samples

      - name: Download feature results
        uses: actions/download-artifact@v2
        with:
          path: results
          name: results

      - name: Compare samples and results
        run: |
          cp -r base/test_samples_osw/baseline/*.csv test/test_samples_osw/baseline
          mkdir test/test_samples_osw/results
          cp -r samples/buildstock*.csv test/test_samples_osw/results
          cp -r results/baseline/results* test/test_samples_osw/results
          
          cp -r base/test_samples_osw/upgrades/*.csv test/test_samples_osw/upgrades
          mkdir test/test_samples_osw/results_upgrades
          cp -r results/upgrades/results* test/test_samples_osw/results_upgrades
          
          pip install numpy
          pip install pandas
          pip install plotly
          pip install kaleido
          
          python test/compare.py -a samples
          
          python test/compare.py -a results
          python test/compare.py -a results -af sum -ac geometry_building_type_recs -x results_output_building_type_sum.csv
          
          python test/compare.py -a visualize -dc geometry_building_type_recs -x results_output_building_type.html
          python test/compare.py -a visualize -dc geometry_foundation_type -x results_output_foundation_type.html
          python test/compare.py -a visualize -dc county -x results_output_county.html
          python test/compare.py -a visualize -dc geometry_building_type_recs -ac county -af sum -x results_output_county_sum.html
          
          mkdir test/test_samples_osw/comparisons/baseline
          cp -r test/test_samples_osw/comparisons/* test/test_samples_osw/comparisons/baseline
          
          python test/compare.py -a results -b test/test_samples_osw/upgrades -f test/test_samples_osw/results_upgrades
          
          python test/compare.py -a visualize -x results_output.html -b test/test_samples_osw/upgrades -f test/test_samples_osw/results_upgrades
          
          mkdir test/test_samples_osw/comparisons/upgrades
          cp -r test/test_samples_osw/comparisons/results_output.csv test/test_samples_osw/comparisons/upgrades
          cp -r test/test_samples_osw/comparisons/results_output.html test/test_samples_osw/comparisons/upgrades

      - name: Upload comparisons
        uses: actions/upload-artifact@v2
        with:
          path: test/test_samples_osw/comparisons
          name: comparisons

  update-results:
    runs-on: ubuntu-latest
    needs: bsb
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Download feature samples
        uses: actions/download-artifact@v2
        with:
          path: samples
          name: samples

      - name: Download feature results
        uses: actions/download-artifact@v2
        with:
          path: results
          name: results

      - name: Commit latest results
        shell: bash        
        run: |
          branch_name="${{ github.head_ref }}"
          git pull origin $branch_name
          cp -r samples/buildstock*.csv test/test_samples_osw/baseline
          cp -r results/baseline/results*.csv test/test_samples_osw/baseline
          cp -r results/upgrades/results*.csv test/test_samples_osw/upgrades
          git add test/test_samples_osw/baseline
          git add test/test_samples_osw/upgrades
          git status
          if [[ $(git diff --cached --exit-code) ]]; then
            git config --global user.email "github-action@users.noreply.github.com"
            git config --global user.name "GitHub Action"
            git commit -m "Latest results."
            echo "Pushing to branch: $branch_name"
            git push -u origin $branch_name
          fi
